"""add physique_evaluations table

Revision ID: 24d95cafe8b7
Revises: 88da8b3459f6
Create Date: 2026-07-06 17:25:38.953389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d95cafe8b7'
down_revision: Union[str, Sequence[str], None] = '88da8b3459f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physique_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('front_image_path', sa.String(), nullable=False),
    sa.Column('side_image_path', sa.String(), nullable=False),
    sa.Column('back_image_path', sa.String(), nullable=False),
    sa.Column('is_valid_submission', sa.Integer(), nullable=False),
    sa.Column('validity_notes', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('training_adjustments', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('physique_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physique_evaluations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_physique_evaluations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physique_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physique_evaluations_user_id'))
        batch_op.drop_index(batch_op.f('ix_physique_evaluations_id'))

    op.drop_table('physique_evaluations')
    # ### end Alembic commands ###
